name: GitHub Classroom Workflow

on: push

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup lean
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"
      - name: classroom autograding
        uses: education/autograding@v1
